<?php

namespace Database\Seeders;

use App\Models\Pregunta;
use Illuminate\Database\Seeder;

class PreguntasMatematicasSeeder extends Seeder
{
    public function run(): void
    {
        $preguntas = [
            [
                'seccion' => 'SECCIÓN 1: OPERACIONES Y PORCENTAJES',
                'pregunta' => 'Una persona gana $12,500 mensuales. ¿Cuánto representa el 18% de su salario?',
                'opcion_a' => '$1,850',
                'opcion_b' => '$2,000',
                'opcion_c' => '$2,250',
                'opcion_d' => '$2,500',
                'respuesta_correcta' => 'c',
                'orden' => 1,
            ],
            [
                'seccion' => 'SECCIÓN 1: OPERACIONES Y PORCENTAJES',
                'pregunta' => 'Un producto cuesta $8,500 y tiene un descuento del 15%. ¿Cuál es su precio final?',
                'opcion_a' => '$7,125',
                'opcion_b' => '$7,225',
                'opcion_c' => '$7,375',
                'opcion_d' => '$7,500',
                'respuesta_correcta' => 'c',
                'orden' => 2,
            ],
            [
                'seccion' => 'SECCIÓN 1: OPERACIONES Y PORCENTAJES',
                'pregunta' => 'Una cantidad de $25,000 aumenta un 12%. ¿Cuál es el nuevo total?',
                'opcion_a' => '$27,000',
                'opcion_b' => '$27,500',
                'opcion_c' => '$28,000',
                'opcion_d' => '$28,500',
                'respuesta_correcta' => 'c',
                'orden' => 3,
            ],
            [
                'seccion' => 'SECCIÓN 1: OPERACIONES Y PORCENTAJES',
                'pregunta' => 'Una persona debe $18,000 y realiza un pago de $4,500. ¿Qué porcentaje de la deuda pagó?',
                'opcion_a' => '20%',
                'opcion_b' => '25%',
                'opcion_c' => '30%',
                'opcion_d' => '35%',
                'respuesta_correcta' => 'b',
                'orden' => 4,
            ],
            [
                'seccion' => 'SECCIÓN 1: OPERACIONES Y PORCENTAJES',
                'pregunta' => 'Un vendedor gana una comisión del 4% por cada préstamo colocado. ¿Cuánto gana por un préstamo de $35,000?',
                'opcion_a' => '$1,200',
                'opcion_b' => '$1,400',
                'opcion_c' => '$1,600',
                'opcion_d' => '$1,750',
                'respuesta_correcta' => 'b',
                'orden' => 5,
            ],
            [
                'seccion' => 'SECCIÓN 2: PROBLEMAS FINANCIEROS',
                'pregunta' => 'Un cliente solicita un préstamo de $20,000. La financiera cobra un interés simple del 10% sobre el monto inicial. ¿Cuánto deberá pagar en total?',
                'opcion_a' => '$21,000',
                'opcion_b' => '$22,000',
                'opcion_c' => '$23,000',
                'opcion_d' => '$24,000',
                'respuesta_correcta' => 'b',
                'orden' => 6,
            ],
            [
                'seccion' => 'SECCIÓN 2: PROBLEMAS FINANCIEROS',
                'pregunta' => 'Un préstamo de $30,000 se pagará en 12 mensualidades iguales, sin considerar intereses. ¿Cuánto sería cada pago?',
                'opcion_a' => '$2,000',
                'opcion_b' => '$2,250',
                'opcion_c' => '$2,500',
                'opcion_d' => '$3,000',
                'respuesta_correcta' => 'c',
                'orden' => 7,
            ],
            [
                'seccion' => 'SECCIÓN 2: PROBLEMAS FINANCIEROS',
                'pregunta' => 'Un cliente debe pagar $2,850 mensuales durante 10 meses. ¿Cuál será el total pagado?',
                'opcion_a' => '$25,850',
                'opcion_b' => '$27,500',
                'opcion_c' => '$28,500',
                'opcion_d' => '$30,000',
                'respuesta_correcta' => 'c',
                'orden' => 8,
            ],
            [
                'seccion' => 'SECCIÓN 2: PROBLEMAS FINANCIEROS',
                'pregunta' => 'Una persona recibe $15,000, pero se le descuenta una comisión del 5%. ¿Cuánto recibe realmente?',
                'opcion_a' => '$14,000',
                'opcion_b' => '$14,250',
                'opcion_c' => '$14,500',
                'opcion_d' => '$14,750',
                'respuesta_correcta' => 'b',
                'orden' => 9,
            ],
            [
                'seccion' => 'SECCIÓN 2: PROBLEMAS FINANCIEROS',
                'pregunta' => 'Una cartera tiene 200 clientes. El 8% presenta atraso en sus pagos. ¿Cuántos clientes están atrasados?',
                'opcion_a' => '8',
                'opcion_b' => '12',
                'opcion_c' => '16',
                'opcion_d' => '20',
                'respuesta_correcta' => 'c',
                'orden' => 10,
            ],
            [
                'seccion' => 'SECCIÓN 3: REGLA DE TRES Y PROPORCIONES',
                'pregunta' => 'Un asesor visita 24 clientes en 4 horas. Manteniendo el mismo ritmo, ¿cuántos clientes visitará en 7 horas?',
                'opcion_a' => '36',
                'opcion_b' => '40',
                'opcion_c' => '42',
                'opcion_d' => '48',
                'respuesta_correcta' => 'c',
                'orden' => 11,
            ],
            [
                'seccion' => 'SECCIÓN 3: REGLA DE TRES Y PROPORCIONES',
                'pregunta' => 'Cinco empleados procesan 150 solicitudes en un día. Al mismo ritmo, ¿cuántas solicitudes procesarán 8 empleados?',
                'opcion_a' => '210',
                'opcion_b' => '220',
                'opcion_c' => '240',
                'opcion_d' => '270',
                'respuesta_correcta' => 'c',
                'orden' => 12,
            ],
            [
                'seccion' => 'SECCIÓN 3: REGLA DE TRES Y PROPORCIONES',
                'pregunta' => 'Si 3 asesores colocan $90,000 en préstamos durante una semana, ¿cuánto colocarían 5 asesores al mismo ritmo?',
                'opcion_a' => '$120,000',
                'opcion_b' => '$135,000',
                'opcion_c' => '$150,000',
                'opcion_d' => '$180,000',
                'respuesta_correcta' => 'c',
                'orden' => 13,
            ],
            [
                'seccion' => 'SECCIÓN 3: REGLA DE TRES Y PROPORCIONES',
                'pregunta' => 'Un vehículo consume 8 litros de gasolina por cada 100 km. ¿Cuántos litros consumirá en 350 km?',
                'opcion_a' => '24',
                'opcion_b' => '26',
                'opcion_c' => '28',
                'opcion_d' => '32',
                'respuesta_correcta' => 'c',
                'orden' => 14,
            ],
            [
                'seccion' => 'SECCIÓN 4: PROMEDIOS Y ANÁLISIS DE DATOS',
                'pregunta' => 'Un asesor colocó $25,000, $32,000, $28,000 y $35,000 durante 4 semanas. ¿Cuál fue su promedio semanal?',
                'opcion_a' => '$28,000',
                'opcion_b' => '$29,000',
                'opcion_c' => '$30,000',
                'opcion_d' => '$31,000',
                'respuesta_correcta' => 'c',
                'orden' => 15,
            ],
            [
                'seccion' => 'SECCIÓN 4: PROMEDIOS Y ANÁLISIS DE DATOS',
                'pregunta' => 'Una empresa tuvo ventas de $80,000, $95,000 y $105,000 durante tres meses. ¿Cuál fue el total?',
                'opcion_a' => '$270,000',
                'opcion_b' => '$275,000',
                'opcion_c' => '$280,000',
                'opcion_d' => '$285,000',
                'respuesta_correcta' => 'c',
                'orden' => 16,
            ],
            [
                'seccion' => 'SECCIÓN 4: PROMEDIOS Y ANÁLISIS DE DATOS',
                'pregunta' => 'Una cartera tenía 500 clientes y aumentó a 575. ¿Cuál fue el crecimiento porcentual?',
                'opcion_a' => '10%',
                'opcion_b' => '12%',
                'opcion_c' => '15%',
                'opcion_d' => '20%',
                'respuesta_correcta' => 'c',
                'orden' => 17,
            ],
            [
                'seccion' => 'SECCIÓN 4: PROMEDIOS Y ANÁLISIS DE DATOS',
                'pregunta' => 'Una ruta tiene 120 clientes. El objetivo es aumentar la cartera un 25%. ¿Cuántos clientes debe tener después del crecimiento?',
                'opcion_a' => '140',
                'opcion_b' => '145',
                'opcion_c' => '150',
                'opcion_d' => '155',
                'respuesta_correcta' => 'c',
                'orden' => 18,
            ],
            [
                'seccion' => 'SECCIÓN 5: PROBLEMAS DE RAZONAMIENTO MATEMÁTICO',
                'pregunta' => 'Una empresa tiene $100,000 disponibles para prestar. Otorga $25,000, $18,000 y $32,000. ¿Cuánto dinero queda disponible?',
                'opcion_a' => '$20,000',
                'opcion_b' => '$25,000',
                'opcion_c' => '$30,000',
                'opcion_d' => '$35,000',
                'respuesta_correcta' => 'b',
                'orden' => 19,
            ],
            [
                'seccion' => 'SECCIÓN 5: PROBLEMAS DE RAZONAMIENTO MATEMÁTICO',
                'pregunta' => 'Un trabajador gana $9,500 de sueldo fijo y $3,200 en comisiones. Si sus gastos mensuales son de $8,750, ¿cuánto dinero le queda?',
                'opcion_a' => '$3,750',
                'opcion_b' => '$3,950',
                'opcion_c' => '$4,000',
                'opcion_d' => '$4,250',
                'respuesta_correcta' => 'a',
                'orden' => 20,
            ],
            [
                'seccion' => 'SECCIÓN 5: PROBLEMAS DE RAZONAMIENTO MATEMÁTICO',
                'pregunta' => 'Una persona tiene ingresos de $20,000. Sus gastos son $6,000, $4,000, $2,000 y $3,000. ¿Qué porcentaje de sus ingresos le queda disponible?',
                'opcion_a' => '20%',
                'opcion_b' => '25%',
                'opcion_c' => '30%',
                'opcion_d' => '35%',
                'respuesta_correcta' => 'c',
                'orden' => 21,
            ],
            [
                'seccion' => 'SECCIÓN 5: PROBLEMAS DE RAZONAMIENTO MATEMÁTICO',
                'pregunta' => 'Una empresa tenía una meta de colocar $500,000. Al finalizar el mes colocó $425,000. ¿Qué porcentaje de la meta alcanzó?',
                'opcion_a' => '75%',
                'opcion_b' => '80%',
                'opcion_c' => '85%',
                'opcion_d' => '90%',
                'respuesta_correcta' => 'c',
                'orden' => 22,
            ],
            [
                'seccion' => 'SECCIÓN 5: PROBLEMAS DE RAZONAMIENTO MATEMÁTICO',
                'pregunta' => 'Un equipo de 4 asesores debe visitar 320 clientes en una semana. Si todos trabajan la misma cantidad, ¿cuántos clientes debe visitar cada asesor?',
                'opcion_a' => '60',
                'opcion_b' => '70',
                'opcion_c' => '80',
                'opcion_d' => '90',
                'respuesta_correcta' => 'c',
                'orden' => 23,
            ],
            [
                'seccion' => 'SECCIÓN 5: PROBLEMAS DE RAZONAMIENTO MATEMÁTICO',
                'pregunta' => 'Un préstamo de $40,000 genera un interés de $6,000. ¿Qué porcentaje de interés representa respecto al préstamo original?',
                'opcion_a' => '10%',
                'opcion_b' => '12%',
                'opcion_c' => '15%',
                'opcion_d' => '20%',
                'respuesta_correcta' => 'c',
                'orden' => 24,
            ],
            [
                'seccion' => 'SECCIÓN 5: PROBLEMAS DE RAZONAMIENTO MATEMÁTICO',
                'pregunta' => 'Una empresa tenía 800 clientes. Perdió el 10%, pero posteriormente consiguió 120 clientes nuevos. ¿Cuántos clientes tiene actualmente?',
                'opcion_a' => '820',
                'opcion_b' => '830',
                'opcion_c' => '840',
                'opcion_d' => '850',
                'respuesta_correcta' => 'c',
                'orden' => 25,
            ],
        ];

        foreach ($preguntas as $datos) {
            Pregunta::updateOrCreate(
                [
                    'examen' => 'matematicas',
                    'orden' => $datos['orden'],
                ],
                [
                    'seccion' => $datos['seccion'],
                    'categoria' => 'Matemáticas',
                    'tipo_pregunta' => 'opcion_multiple',
                    'pregunta' => $datos['pregunta'],
                    'opcion_a' => $datos['opcion_a'],
                    'opcion_b' => $datos['opcion_b'],
                    'opcion_c' => $datos['opcion_c'],
                    'opcion_d' => $datos['opcion_d'],
                    'opcion_e' => null,
                    'respuesta_correcta' => $datos['respuesta_correcta'],
                    'criterio_evaluacion' => null,
                    'calificacion_automatica' => true,
                    'valor' => 1,
                    'puntaje_maximo' => 1,
                    'activa' => true,
                ]
            );
        }

        $this->command?->info('Las 25 preguntas de Matemáticas fueron cargadas correctamente.');
    }
}
